### ISSUE TITLE
People YAMLS in Wrong Folder

### ISSUE THREAD

**Issue by liam-middlebrook** [decause/bizlegfoss#18]
Some student YAML files (including my own) are currently stored in the `people/2014/` folder, they should be in the `people/2015` folder.

I think we should fix this once all of the student yamls are online, that way there is little confusion.

**Comment by Nolski** [comment]
@amm4108 @brendanwhitfield @Berulacks @CCoffie @chrisknepper @decause (lolololol) @msoucy @wywin

**Comment by msoucy** [comment]
See #39

**Comment by liam-middlebrook** [comment]
See #41

**Comment by liam-middlebrook** [comment]
@decause you are the only person with a YAML left in the 2014 folder. Is this intended? If so please close this issue.

**Comment by liam-middlebrook** [comment]
@decause please fix.
