### ISSUE TITLE
Setup Travis-CI?

### ISSUE THREAD

**Issue by decause** [decause/bizlegfoss#4]
hflossk used to have this. Can we haz too?

@liam-middlebrook @ryansb

**Comment by ryansb** [comment]
Yeah, assign this to me and I'll file a PR.

**Comment by liam-middlebrook** [comment]
I'll get to this as soon as @ryansb merges [ofCourse/#28](https://github.com/ryansb/ofCourse/pull/28)

**Comment by ryansb** [comment]
Closing this issue, resolved in #128

**Comment by ryansb** [comment]
Oh...don't have perms to close this.

**Comment by decause** [comment]
@ryansb++
