### ISSUE TITLE
Move NDA + Contract Class part to Spring 2015 RIT Career fair

### ISSUE THREAD

**Issue by kocsenc** [decause/bizlegfoss#62]
We are talking about NDA's and contracts in the bizlegfoss class. This issue is created to propose moving the time in which we talk about this during, or before career fair @ rit (2015 spring).

The [career fair is during March 2015 4th-5th ](https://www.rit.edu/emcs/oce/employer/career-fairs-all-majors#dates)

**Comment by decause** [comment]
Was not able to move this in time

:crying_cat_face:
