### ISSUE TITLE
'Fork me on Github' link is not clickable when navbar is collapsed for smaller screens 

### ISSUE THREAD

**Issue by dropofwill** [decause/bizlegfoss#65]
The list items from the nabber cover the 'Fork me on Github' link when it is collapsed for smaller screens. making it impossible to click:

![screen shot 2015-02-06 at 1 33 46 pm](https://cloud.githubusercontent.com/assets/3129448/6085105/d2640a58-ae04-11e4-8c25-454a31da7302.png)

It's an easy enough fix with a couple lines of css (adjust the width of the li's or the z-index/positioning =), but I'm not super familiar with Bootstrap, so there might be a way to fix this with its built in classes.

Confirmed on Safari 8 in OS X and Chromium 40 in Arch.

**Comment by liam-middlebrook** [comment]
Can you move this issue to [ryansb/ofCourse](https://github.com/ryansb/ofCourse)? This is an issue with the base templating created in ofCourse websites.

**Comment by dropofwill** [comment]
Sure, added it [here](https://github.com/ryansb/ofCourse/issues/20).

Just curious, are the template files in this repo not used? Or will every one of these content sites need to be updated when changes are made to the templates?

**Comment by liam-middlebrook** [comment]
Every one of the content sites will need to be updated. ofCourse currently doesn't have a nice way to propagate changes like this in a convenient way.

**Comment by ryansb** [comment]
Now it does! `ofcourse sync`

**Comment by Nolski** [comment]
:rocket:
